# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=150)),
                ('printed', models.CharField(max_length=150)),
                ('height', models.CharField(choices=[(b'High', b'High'), (b'Mid', b'Mid'), (b'Low', b'Low')], max_length=1)),
                ('thickness', models.CharField(choices=[(b'Thick', b'Thick'), (b'Thin', b'Thin')], max_length=1)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
