# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='printed',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='thickness',
            field=models.IntegerField(),
        ),
    ]
